### ISSUE TITLE
Proposal : adding a test gate before the build

### ISSUE THREAD

**Issue by borisschapira** [hydepress/jekyll-deploy#1]
Regarding the build : https://github.com/hydepress/jekyll-deploy/blob/master/continuous-integration.md#2-the-test-script

You can run a little test ton ensure that your content is YAML-valid before launching the Jekyll Build :

```
      @posts = []
      Dir.glob('_posts/**/*.{md,markdown}').each do |p|
          @posts << p
      end
      @posts.each do |post|
        begin
          YAML.load_file(post)
        rescue Exception => e
          puts post
          puts e.message
          raise "Post syntax is not valid"
        end
      end
      puts "#{@posts.size} valid posts"
```

I wanted to propose a PR but I don't know if you're interested and how that could fit into your writing.

**Comment by geraldb** [comment]
@borisschapira  Great. Please add a pull request **upstream** - see [jekyll/site/_docs/continuous-integration.md](https://github.com/jekyll/jekyll/blob/master/site/_docs/continuous-integration.md). The book here is just a reformated downstream copy and your changes will get added with the next upstream update. Thanks. Cheers.
